[2024-12-06T09:42:52.867+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T09:42:52.884+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1.send_to_kafka manual__2024-12-06T09:36:21.393654+00:00 [queued]>
[2024-12-06T09:42:52.894+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1.send_to_kafka manual__2024-12-06T09:36:21.393654+00:00 [queued]>
[2024-12-06T09:42:52.895+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-06T09:42:52.908+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): send_to_kafka> on 2024-12-06 09:36:21.393654+00:00
[2024-12-06T09:42:52.913+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=561) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T09:42:52.915+0000] {standard_task_runner.py:72} INFO - Started process 562 to run task
[2024-12-06T09:42:52.915+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'send_to_kafka', 'manual__2024-12-06T09:36:21.393654+00:00', '--job-id', '421', '--raw', '--subdir', 'DAGS_FOLDER/dag1_producer_mongo.py', '--cfg-path', '/tmp/tmp170ag1n2']
[2024-12-06T09:42:52.917+0000] {standard_task_runner.py:105} INFO - Job 421: Subtask send_to_kafka
[2024-12-06T09:42:52.959+0000] {task_command.py:467} INFO - Running <TaskInstance: dag1.send_to_kafka manual__2024-12-06T09:36:21.393654+00:00 [running]> on host bc436253e42c
[2024-12-06T09:42:53.054+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T09:36:21.393654+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T09:36:21.393654+00:00'
[2024-12-06T09:42:53.056+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T09:43:18.100+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-12-06T09:43:18.101+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-06T09:43:18.102+0000] {process_utils.py:132} INFO - Sending 15 to group 562. PIDs of all processes in the group: [562]
[2024-12-06T09:43:18.103+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 562
[2024-12-06T09:43:18.104+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-06T09:43:18.124+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T09:43:18.691+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=562, status='terminated', exitcode=0, started='09:42:52') (562) terminated with exit code 0
