[2024-12-04T14:09:18.480+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T14:09:18.502+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_producer.send_to_kafka manual__2024-12-04T14:04:13.983170+00:00 [queued]>
[2024-12-04T14:09:18.515+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_producer.send_to_kafka manual__2024-12-04T14:04:13.983170+00:00 [queued]>
[2024-12-04T14:09:18.515+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-04T14:09:18.534+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): send_to_kafka> on 2024-12-04 14:04:13.983170+00:00
[2024-12-04T14:09:18.539+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1181) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T14:09:18.542+0000] {standard_task_runner.py:72} INFO - Started process 1182 to run task
[2024-12-04T14:09:18.542+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_producer', 'send_to_kafka', 'manual__2024-12-04T14:04:13.983170+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/test_dags.py', '--cfg-path', '/tmp/tmp68_86os1']
[2024-12-04T14:09:18.545+0000] {standard_task_runner.py:105} INFO - Job 260: Subtask send_to_kafka
[2024-12-04T14:09:18.602+0000] {task_command.py:467} INFO - Running <TaskInstance: test_producer.send_to_kafka manual__2024-12-04T14:04:13.983170+00:00 [running]> on host bc436253e42c
[2024-12-04T14:09:18.738+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_producer' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T14:04:13.983170+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T14:04:13.983170+00:00'
[2024-12-04T14:09:18.740+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T14:09:18.795+0000] {logging_mixin.py:190} INFO - {"_id": "6707fa42840c437097f7b593", "travel": 3, "payer": 1, "amount": 26092, "code_departure": "SIN", "code_arrival": "ICN", "number_of_passengers": 4, "passengers": [{"passenger": "Zoe Barnaby", "birth_date": "1993-09-24"}, {"name": "Ružica Ivančević", "birth_date": "1995-09-02"}, {"name": "Timm Raabe", "birth_date": "1976-11-19"}, {"name": "Greta Oorschot", "birth_date": "1993-08-19"}], "created": "2024-10-10T16:01:06.102000"}
[2024-12-04T14:09:18.796+0000] {logging_mixin.py:190} INFO -  строку  {"_id": "6707fa42840c437097f7b593", "travel": 3, "payer": 1, "amount": 26092, "code_departure": "SIN", "code_arrival": "ICN", "number_of_passengers": 4, "passengers": [{"passenger": "Zoe Barnaby", "birth_date": "1993-09-24"}, {"name": "Ružica Ivančević", "birth_date": "1995-09-02"}, {"name": "Timm Raabe", "birth_date": "1976-11-19"}, {"name": "Greta Oorschot", "birth_date": "1993-08-19"}], "created": "2024-10-10T16:01:06.102000"}
[2024-12-04T14:09:18.797+0000] {logging_mixin.py:190} INFO - {'_id': '6707fa42840c437097f7b593', 'travel': 3, 'payer': 1, 'amount': 26092, 'code_departure': 'SIN', 'code_arrival': 'ICN', 'number_of_passengers': 4, 'passengers': [{'name': 'Zoe Barnaby', 'birth_date': '1993-09-24'}, {'name': 'Ružica Ivančević', 'birth_date': '1995-09-02'}, {'name': 'Timm Raabe', 'birth_date': '1976-11-19'}, {'name': 'Greta Oorschot', 'birth_date': '1993-08-19'}], 'created': '2024-10-10T16:01:06.102000'}
[2024-12-04T14:09:18.815+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "fastavro/_write.pyx", line 370, in fastavro._write.write_record
TypeError: Expected dict, got str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_dags.py", line 107, in test_producer
    value=avro_serializer(
          ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/confluent_kafka/schema_registry/avro.py", line 308, in __call__
    schemaless_writer(fo, self._parsed_schema, value)
  File "fastavro/_write.pyx", line 811, in fastavro._write.schemaless_writer
  File "fastavro/_write.pyx", line 465, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 386, in fastavro._write.write_record
AttributeError: 'str' object has no attribute 'get'
[2024-12-04T14:09:18.834+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=test_producer, task_id=send_to_kafka, run_id=manual__2024-12-04T14:04:13.983170+00:00, execution_date=20241204T140413, start_date=20241204T140918, end_date=20241204T140918
[2024-12-04T14:09:18.854+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T14:09:18.855+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 260 for task send_to_kafka ('str' object has no attribute 'get'; 1182)
Traceback (most recent call last):
  File "fastavro/_write.pyx", line 370, in fastavro._write.write_record
TypeError: Expected dict, got str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_dags.py", line 107, in test_producer
    value=avro_serializer(
          ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/confluent_kafka/schema_registry/avro.py", line 308, in __call__
    schemaless_writer(fo, self._parsed_schema, value)
  File "fastavro/_write.pyx", line 811, in fastavro._write.schemaless_writer
  File "fastavro/_write.pyx", line 465, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 386, in fastavro._write.write_record
AttributeError: 'str' object has no attribute 'get'
[2024-12-04T14:09:18.878+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-04T14:09:18.905+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T14:09:18.907+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
