[2024-12-07T21:51:01.357+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-07T21:51:01.375+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag2_kafka_s3.test_s3_connection manual__2024-12-07T21:50:59.684629+00:00 [queued]>
[2024-12-07T21:51:01.384+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag2_kafka_s3.test_s3_connection manual__2024-12-07T21:50:59.684629+00:00 [queued]>
[2024-12-07T21:51:01.385+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-07T21:51:01.400+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_s3_connection> on 2024-12-07 21:50:59.684629+00:00
[2024-12-07T21:51:01.406+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1289) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-07T21:51:01.408+0000] {standard_task_runner.py:72} INFO - Started process 1291 to run task
[2024-12-07T21:51:01.408+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag2_kafka_s3', 'test_s3_connection', 'manual__2024-12-07T21:50:59.684629+00:00', '--job-id', '614', '--raw', '--subdir', 'DAGS_FOLDER/dag2_kafka_s3.py', '--cfg-path', '/tmp/tmpniet7cv5']
[2024-12-07T21:51:01.411+0000] {standard_task_runner.py:105} INFO - Job 614: Subtask test_s3_connection
[2024-12-07T21:51:01.457+0000] {task_command.py:467} INFO - Running <TaskInstance: dag2_kafka_s3.test_s3_connection manual__2024-12-07T21:50:59.684629+00:00 [running]> on host d7d86e3077c3
[2024-12-07T21:51:01.559+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag2_kafka_s3' AIRFLOW_CTX_TASK_ID='test_s3_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T21:50:59.684629+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T21:50:59.684629+00:00'
[2024-12-07T21:51:01.561+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-07T21:51:02.265+0000] {logging_mixin.py:190} INFO - Подключение успешно. Найдено 7 бакетов: ['levs-test', 'mybucket', 'reciept-bucket', 'spark', 'test-bucket', 'travel', 'users-add']
[2024-12-07T21:51:02.267+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-07T21:51:02.278+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-07T21:51:02.279+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag2_kafka_s3, task_id=test_s3_connection, run_id=manual__2024-12-07T21:50:59.684629+00:00, execution_date=20241207T215059, start_date=20241207T215101, end_date=20241207T215102
[2024-12-07T21:51:02.307+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-07T21:51:02.338+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-07T21:51:02.340+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
