[2024-12-04T13:25:22.081+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T13:25:22.101+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: consume.consume manual__2024-12-04T13:25:21.206209+00:00 [queued]>
[2024-12-04T13:25:22.111+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: consume.consume manual__2024-12-04T13:25:21.206209+00:00 [queued]>
[2024-12-04T13:25:22.112+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-04T13:25:22.127+0000] {taskinstance.py:2889} INFO - Executing <Task(ConsumeFromTopicOperator): consume> on 2024-12-04 13:25:21.206209+00:00
[2024-12-04T13:25:22.132+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=565) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T13:25:22.133+0000] {standard_task_runner.py:72} INFO - Started process 566 to run task
[2024-12-04T13:25:22.134+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'consume', 'consume', 'manual__2024-12-04T13:25:21.206209+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/test_dags3.py', '--cfg-path', '/tmp/tmpjner4xez']
[2024-12-04T13:25:22.135+0000] {standard_task_runner.py:105} INFO - Job 247: Subtask consume
[2024-12-04T13:25:22.179+0000] {task_command.py:467} INFO - Running <TaskInstance: consume.consume manual__2024-12-04T13:25:21.206209+00:00 [running]> on host bc436253e42c
[2024-12-04T13:25:22.271+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='consume' AIRFLOW_CTX_TASK_ID='consume' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T13:25:21.206209+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T13:25:21.206209+00:00'
[2024-12-04T13:25:22.272+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T13:25:22.300+0000] {base.py:84} INFO - Retrieving connection 'kafka_connection'
[2024-12-04T13:25:22.301+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/operators/consume.py", line 130, in execute
    consumer = KafkaConsumerHook(topics=self.topics, kafka_config_id=self.kafka_config_id).get_consumer()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/hooks/consume.py", line 43, in get_consumer
    consumer = self.get_conn
               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/hooks/base.py", line 66, in get_conn
    return self._get_client(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/hooks/consume.py", line 39, in _get_client
    return Consumer(config)
           ^^^^^^^^^^^^^^^^
ValueError: Failed to create consumer: group.id must be set
[2024-12-04T13:25:22.315+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=consume, task_id=consume, run_id=manual__2024-12-04T13:25:21.206209+00:00, execution_date=20241204T132521, start_date=20241204T132522, end_date=20241204T132522
[2024-12-04T13:25:22.332+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T13:25:22.333+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 247 for task consume (Failed to create consumer: group.id must be set; 566)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/operators/consume.py", line 130, in execute
    consumer = KafkaConsumerHook(topics=self.topics, kafka_config_id=self.kafka_config_id).get_consumer()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/hooks/consume.py", line 43, in get_consumer
    consumer = self.get_conn
               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/hooks/base.py", line 66, in get_conn
    return self._get_client(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/kafka/hooks/consume.py", line 39, in _get_client
    return Consumer(config)
           ^^^^^^^^^^^^^^^^
ValueError: Failed to create consumer: group.id must be set
[2024-12-04T13:25:22.349+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-04T13:25:22.369+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T13:25:22.371+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
