[2024-12-09T08:29:38.218+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T08:29:38.240+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_kafka_avro.test_s3_connection manual__2024-12-09T08:29:36.525760+00:00 [queued]>
[2024-12-09T08:29:38.253+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_kafka_avro.test_s3_connection manual__2024-12-09T08:29:36.525760+00:00 [queued]>
[2024-12-09T08:29:38.254+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-09T08:29:38.274+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_s3_connection> on 2024-12-09 08:29:36.525760+00:00
[2024-12-09T08:29:38.279+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=786) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T08:29:38.282+0000] {standard_task_runner.py:72} INFO - Started process 787 to run task
[2024-12-09T08:29:38.282+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 's3_to_kafka_avro', 'test_s3_connection', 'manual__2024-12-09T08:29:36.525760+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dag3_s3_kafka.py', '--cfg-path', '/tmp/tmpof0b_tjc']
[2024-12-09T08:29:38.285+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask test_s3_connection
[2024-12-09T08:29:38.340+0000] {task_command.py:467} INFO - Running <TaskInstance: s3_to_kafka_avro.test_s3_connection manual__2024-12-09T08:29:36.525760+00:00 [running]> on host c23cf8b5bd6f
[2024-12-09T08:29:38.462+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_kafka_avro' AIRFLOW_CTX_TASK_ID='test_s3_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T08:29:36.525760+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T08:29:36.525760+00:00'
[2024-12-09T08:29:38.464+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T08:29:38.764+0000] {logging_mixin.py:190} INFO - Подключение успешно. Найдено 7 бакетов: ['levs-test', 'mybucket', 'reciept-bucket', 'spark', 'test-bucket', 'travel', 'users-add']
[2024-12-09T08:29:38.766+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-09T08:29:38.778+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T08:29:38.779+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=s3_to_kafka_avro, task_id=test_s3_connection, run_id=manual__2024-12-09T08:29:36.525760+00:00, execution_date=20241209T082936, start_date=20241209T082938, end_date=20241209T082938
[2024-12-09T08:29:38.820+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-09T08:29:38.838+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-09T08:29:38.840+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
