[2024-12-09T11:10:46.305+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T11:10:46.337+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag2_kafka_s3.test_s3_connection manual__2024-12-09T11:10:41.957483+00:00 [queued]>
[2024-12-09T11:10:46.356+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag2_kafka_s3.test_s3_connection manual__2024-12-09T11:10:41.957483+00:00 [queued]>
[2024-12-09T11:10:46.357+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-09T11:10:46.391+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_s3_connection> on 2024-12-09 11:10:41.957483+00:00
[2024-12-09T11:10:46.402+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3153) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T11:10:46.405+0000] {standard_task_runner.py:72} INFO - Started process 3155 to run task
[2024-12-09T11:10:46.407+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag2_kafka_s3', 'test_s3_connection', 'manual__2024-12-09T11:10:41.957483+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag2_kafka_s3.py', '--cfg-path', '/tmp/tmpbt8ncbrq']
[2024-12-09T11:10:46.414+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask test_s3_connection
[2024-12-09T11:10:46.511+0000] {task_command.py:467} INFO - Running <TaskInstance: dag2_kafka_s3.test_s3_connection manual__2024-12-09T11:10:41.957483+00:00 [running]> on host c23cf8b5bd6f
[2024-12-09T11:10:46.749+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag2_kafka_s3' AIRFLOW_CTX_TASK_ID='test_s3_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T11:10:41.957483+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T11:10:41.957483+00:00'
[2024-12-09T11:10:46.753+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T11:10:48.531+0000] {logging_mixin.py:190} INFO - Подключение успешно. Найдено 7 бакетов: ['levs-test', 'mybucket', 'reciept-bucket', 'spark', 'test-bucket', 'travel', 'users-add']
[2024-12-09T11:10:48.565+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-09T11:10:48.619+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T11:10:48.634+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag2_kafka_s3, task_id=test_s3_connection, run_id=manual__2024-12-09T11:10:41.957483+00:00, execution_date=20241209T111041, start_date=20241209T111046, end_date=20241209T111048
[2024-12-09T11:10:48.751+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-09T11:10:48.862+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-09T11:10:48.871+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
